export default [
    {value: 'CIS', label: 'СНГ'},
    {value: 'CIS-KZ', label: 'СНГ без КЗ'},
    {value: 'AU', label: 'Австралия'},
    {value: 'AT', label: 'Австрия'},
    {value: 'AZ', label: 'Азербайджан'},
    {value: 'AX', label: 'Аландские острова'},
    {value: 'AL', label: 'Албания'},
    {value: 'DZ', label: 'Алжир'},
    {value: 'VI', label: 'Виргинские Острова (США)'},
    {value: 'AS', label: 'Американское Самоа'},
    {value: 'AI', label: 'Ангилья'},
    {value: 'AO', label: 'Ангола'},
    {value: 'AD', label: 'Андорра'},
    {value: 'AQ', label: 'Антарктика'},
    {value: 'AG', label: 'Антигуа и Барбуда'},
    {value: 'AR', label: 'Аргентина'},
    {value: 'AM', label: 'Армения'},
    {value: 'AW', label: 'Аруба'},
    {value: 'AF', label: 'Афганистан'},
    {value: 'BS', label: 'Багамские Острова'},
    {value: 'BD', label: 'Бангладеш'},
    {value: 'BB', label: 'Барбадос'},
    {value: 'BH', label: 'Бахрейн'},
    {value: 'BZ', label: 'Белиз'},
    {value: 'BY', label: 'Белоруссия'},
    {value: 'BE', label: 'Бельгия'},
    {value: 'BJ', label: 'Бенин'},
    {value: 'BM', label: 'Бермуды'},
    {value: 'BG', label: 'Болгария'},
    {value: 'BO', label: 'Боливия'},
    {value: 'BQ', label: 'Бонайре, Синт-Эстатиус и Саба'},
    {value: 'BA', label: 'Босния и Герцеговина'},
    {value: 'BW', label: 'Ботсвана'},
    {value: 'BR', label: 'Бразилия'},
    {value: 'IO', label: 'Британская территория в Индийском океане'},
    {value: 'VG', label: 'Виргинские Острова (Великобритания)'},
    {value: 'BN', label: 'Бруней'},
    {value: 'BF', label: 'Буркина-Фасо'},
    {value: 'BI', label: 'Бурунди'},
    {value: 'BT', label: 'Бутан'},
    {value: 'VU', label: 'Вануату'},
    {value: 'VA', label: 'Ватикан'},
    {value: 'GB', label: 'Великобритания'},
    {value: 'HU', label: 'Венгрия'},
    {value: 'VE', label: 'Венесуэла'},
    {value: 'UM', label: 'Внешние малые острова США'},
    {value: 'TL', label: 'Восточный Тимор'},
    {value: 'VN', label: 'Вьетнам'},
    {value: 'GA', label: 'Габон'},
    {value: 'HT', label: 'Гаити'},
    {value: 'GY', label: 'Гайана'},
    {value: 'GM', label: 'Гамбия'},
    {value: 'GH', label: 'Гана'},
    {value: 'GP', label: 'Гваделупа'},
    {value: 'GT', label: 'Гватемала'},
    {value: 'GF', label: 'Гвиана'},
    {value: 'GN', label: 'Гвинея'},
    {value: 'GW', label: 'Гвинея-Бисау'},
    {value: 'DE', label: 'Германия'},
    {value: 'GG', label: 'Гернси'},
    {value: 'GI', label: 'Гибралтар'},
    {value: 'HN', label: 'Гондурас'},
    {value: 'HK', label: 'Гонконг'},
    {value: 'GD', label: 'Гренада'},
    {value: 'GL', label: 'Гренландия'},
    {value: 'GR', label: 'Греция'},
    {value: 'GE', label: 'Грузия'},
    {value: 'GU', label: 'Гуам'},
    {value: 'DK', label: 'Дания'},
    {value: 'JE', label: 'Джерси'},
    {value: 'DJ', label: 'Джибути'},
    {value: 'DM', label: 'Доминика'},
    {value: 'DO', label: 'Доминиканская Республика'},
    {value: 'CD', label: 'ДР Конго'},
    {value: 'EU', label: 'Флаг ЕС Европейский союз'},
    {value: 'EG', label: 'Египет'},
    {value: 'ZM', label: 'Замбия'},
    {value: 'EH', label: 'САДР'},
    {value: 'ZW', label: 'Зимбабве'},
    {value: 'IL', label: 'Израиль'},
    {value: 'IN', label: 'Индия'},
    {value: 'ID', label: 'Индонезия'},
    {value: 'JO', label: 'Иордания'},
    {value: 'IQ', label: 'Ирак'},
    {value: 'IR', label: 'Иран'},
    {value: 'IE', label: 'Ирландия'},
    {value: 'IS', label: 'Исландия'},
    {value: 'ES', label: 'Испания'},
    {value: 'IT', label: 'Италия'},
    {value: 'YE', label: 'Йемен'},
    {value: 'CV', label: 'Кабо-Верде'},
    {value: 'KZ', label: 'Казахстан'},
    {value: 'KY', label: 'Острова Кайман'},
    {value: 'KH', label: 'Камбоджа'},
    {value: 'CM', label: 'Камерун'},
    {value: 'CA', label: 'Канада'},
    {value: 'QA', label: 'Катар'},
    {value: 'KE', label: 'Кения'},
    {value: 'CY', label: 'Кипр'},
    {value: 'KG', label: 'Киргизия'},
    {value: 'KI', label: 'Кирибати'},
    {value: 'TW', label: 'Китайская Республика'},
    {value: 'KP', label: 'КНДР (Корейская Народно-Демократическая Республика)'},
    {value: 'CN', label: 'Китай (Китайская Народная Республика)'},
    {value: 'CC', label: 'Кокосовые острова'},
    {value: 'CO', label: 'Колумбия'},
    {value: 'KM', label: 'Коморы'},
    {value: 'CR', label: 'Коста-Рика'},
    {value: 'CI', label: 'Кот-д\'Ивуар'},
    {value: 'CU', label: 'Куба'},
    {value: 'KW', label: 'Кувейт'},
    {value: 'CW', label: 'Кюрасао'},
    {value: 'LA', label: 'Лаос'},
    {value: 'LV', label: 'Латвия'},
    {value: 'LS', label: 'Лесото'},
    {value: 'LR', label: 'Либерия'},
    {value: 'LB', label: 'Ливан'},
    {value: 'LY', label: 'Ливия'},
    {value: 'LT', label: 'Литва'},
    {value: 'LI', label: 'Лихтенштейн'},
    {value: 'LU', label: 'Люксембург'},
    {value: 'MU', label: 'Маврикий'},
    {value: 'MR', label: 'Мавритания'},
    {value: 'MG', label: 'Мадагаскар'},
    {value: 'YT', label: 'Майотта'},
    {value: 'MO', label: 'Макао'},
    {value: 'MK', label: 'Северная Македония'},
    {value: 'MW', label: 'Малави'},
    {value: 'MY', label: 'Малайзия'},
    {value: 'ML', label: 'Мали'},
    {value: 'MV', label: 'Мальдивы'},
    {value: 'MT', label: 'Мальта'},
    {value: 'MA', label: 'Марокко'},
    {value: 'MQ', label: 'Мартиника'},
    {value: 'MH', label: 'Маршалловы Острова'},
    {value: 'MX', label: 'Мексика'},
    {value: 'FM', label: 'Микронезия'},
    {value: 'MZ', label: 'Мозамбик'},
    {value: 'MD', label: 'Молдавия'},
    {value: 'MC', label: 'Монако'},
    {value: 'MN', label: 'Монголия'},
    {value: 'MS', label: 'Монтсеррат'},
    {value: 'MM', label: 'Мьянма'},
    {value: 'NA', label: 'Намибия'},
    {value: 'NR', label: 'Науру'},
    {value: 'NP', label: 'Непал'},
    {value: 'NE', label: 'Нигер'},
    {value: 'NG', label: 'Нигерия'},
    {value: 'NL', label: 'Нидерланды'},
    {value: 'NI', label: 'Никарагуа'},
    {value: 'NU', label: 'Ниуэ'},
    {value: 'NZ', label: 'Новая Зеландия'},
    {value: 'NC', label: 'Новая Каледония'},
    {value: 'NO', label: 'Норвегия'},
    {value: 'AE', label: 'ОАЭ'},
    {value: 'OM', label: 'Оман'},
    {value: 'BV', label: 'Остров Буве'},
    {value: 'IM', label: 'Остров Мэн'},
    {value: 'CK', label: 'Острова Кука'},
    {value: 'NF', label: 'Остров Норфолк'},
    {value: 'CX', label: 'Остров Рождества'},
    {value: 'PN', label: 'Острова Питкэрн'},
    {value: 'SH', label: 'Острова Святой Елены, Вознесения и Тристан-да-Кунья'},
    {value: 'PK', label: 'Пакистан'},
    {value: 'PW', label: 'Палау'},
    {value: 'PS', label: 'Государство Палестина'},
    {value: 'PA', label: 'Панама'},
    {value: 'PG', label: 'Папуа &mdash; Новая Гвинея'},
    {value: 'PY', label: 'Парагвай'},
    {value: 'PE', label: 'Перу'},
    {value: 'PL', label: 'Польша'},
    {value: 'PT', label: 'Португалия'},
    {value: 'PR', label: 'Пуэрто-Рико'},
    {value: 'CG', label: 'Республика Конго'},
    {value: 'KR', label: 'Республика Корея'},
    {value: 'RE', label: 'Реюньон'},
    {value: 'RU', label: 'Россия'},
    {value: 'RW', label: 'Руанда'},
    {value: 'RO', label: 'Румыния'},
    {value: 'SV', label: 'Сальвадор'},
    {value: 'WS', label: 'Самоа'},
    {value: 'SM', label: 'Сан-Марино'},
    {value: 'ST', label: 'Сан-Томе и Принсипи'},
    {value: 'SA', label: 'Саудовская Аравия'},
    {value: 'SZ', label: 'Эсватини'},
    {value: 'MP', label: 'Северные Марианские Острова'},
    {value: 'SC', label: 'Сейшельские Острова'},
    {value: 'BL', label: 'Сен-Бартелеми'},
    {value: 'MF', label: 'Сен-Мартен'},
    {value: 'PM', label: 'Сен-Пьер и Микелон'},
    {value: 'SN', label: 'Сенегал'},
    {value: 'VC', label: 'Сент-Винсент и Гренадины'},
    {value: 'KN', label: 'Сент-Китс и Невис'},
    {value: 'LC', label: 'Сент-Люсия'},
    {value: 'RS', label: 'Сербия'},
    {value: 'SG', label: 'Сингапур'},
    {value: 'SX', label: 'Синт-Мартен'},
    {value: 'SY', label: 'Сирия'},
    {value: 'SK', label: 'Словакия'},
    {value: 'SI', label: 'Словения'},
    {value: 'SB', label: 'Соломоновы Острова'},
    {value: 'SO', label: 'Сомали'},
    {value: 'SD', label: 'Судан'},
    {value: 'SR', label: 'Суринам'},
    {value: 'US', label: 'США'},
    {value: 'SL', label: 'Сьерра-Леоне'},
    {value: 'TJ', label: 'Таджикистан'},
    {value: 'TH', label: 'Таиланд'},
    {value: 'TZ', label: 'Танзания'},
    {value: 'TC', label: 'Теркс и Кайкос'},
    {value: 'TG', label: 'Того'},
    {value: 'TK', label: 'Токелау'},
    {value: 'TO', label: 'Тонга'},
    {value: 'TT', label: 'Тринидад и Тобаго'},
    {value: 'TV', label: 'Тувалу'},
    {value: 'TN', label: 'Тунис'},
    {value: 'TM', label: 'Туркмения'},
    {value: 'TR', label: 'Турция'},
    {value: 'UG', label: 'Уганда'},
    {value: 'UZ', label: 'Узбекистан'},
    {value: 'UA', label: 'Украина'},
    {value: 'WF', label: 'Уоллис и Футуна'},
    {value: 'UY', label: 'Уругвай'},
    {value: 'FO', label: 'Фарерские острова'},
    {value: 'FJ', label: 'Фиджи'},
    {value: 'PH', label: 'Филиппины'},
    {value: 'FI', label: 'Финляндия'},
    {value: 'FK', label: 'Фолклендские острова'},
    {value: 'FR', label: 'Франция'},
    {value: 'PF', label: 'Французская Полинезия'},
    {value: 'TF', label: 'Французские Южные и Антарктические территории'},
    {value: 'HM', label: 'Херд и Макдональд'},
    {value: 'HR', label: 'Хорватия'},
    {value: 'CF', label: 'ЦАР'},
    {value: 'TD', label: 'Чад'},
    {value: 'ME', label: 'Черногория'},
    {value: 'CZ', label: 'Чехия'},
    {value: 'CL', label: 'Чили'},
    {value: 'CH', label: 'Швейцария'},
    {value: 'SE', label: 'Швеция'},
    {value: 'SJ', label: 'Флаг Шпицбергена и Ян-Майена Шпицберген и Ян-Майен'},
    {value: 'LK', label: 'Шри-Ланка'},
    {value: 'EC', label: 'Эквадор'},
    {value: 'GQ', label: 'Экваториальная Гвинея'},
    {value: 'ER', label: 'Эритрея'},
    {value: 'EE', label: 'Эстония'},
    {value: 'ET', label: 'Эфиопия'},
    {value: 'ZA', label: 'ЮАР'},
    {value: 'GS', label: 'Южная Георгия и Южные Сандвичевы Острова'},
    {value: 'SS', label: 'Южный Судан'},
    {value: 'JM', label: 'Ямайка'},
    {value: 'JP', label: 'Япония'}
]